const manifest = @import("upstream_manifest");

pub const upstream: manifest.Source = .{
    .name = "etcd/raft",
    .repository = "https://github.com/etcd-io/raft",
    .revision = "56e32004b1af3a4cb625fbfe5dbca24fb6023d09",
    .license = "Apache-2.0",
    .policy = "Primary baseline; adapt behavior with attribution.",
    .cases = &.{
        .{
            .id = "raft_test.go::TestLeaderElectionPreVote",
            .path = "raft_test.go",
            .category = "pre-vote",
            .status = .adapted,
            .rationale = "Covers successful and quorum-starved pre-vote elections.",
        },
        .{
            .id = "raft_test.go::TestPreVoteFromAnyState",
            .path = "raft_test.go",
            .category = "pre-vote",
            .status = .adapted,
            .rationale = "Covers pre-vote immutability across all Raft roles.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferToUpToDateNode",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Transfers leadership to a fully replicated voter.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferToUpToDateNodeFromFollower",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Covers follower forwarding of transfer requests.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferToSlowFollower",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Catches up the transferee before TimeoutNow.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferAfterSnapshot",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .blocked,
            .rationale = "The deterministic network does not yet support snapshot safety checks.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferToSelf",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Treats transfer to the current leader as a no-op.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferToNonExistingNode",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Ignores a transferee outside the current configuration.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferTimeout",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Aborts a stalled transfer after the election timeout.",
        },
        .{
            .id = "raft_test.go::TestLeaderTransferIgnoreProposal",
            .path = "raft_test.go",
            .category = "leadership-transfer",
            .status = .adapted,
            .rationale = "Rejects proposals while leadership transfer is pending.",
        },
    },
};
