//! Minimal simulated network for Raft integration tests.
//!
//! Ports the parts of `ref/raftpp/tests/harness/network.{h,cc}` we need to
//! exercise the FSM with multi-node clusters. Each `Peer` wraps a `Raft`
//! instance plus its `MemoryStorage`; `Network` routes messages by `to` and
//! recursively dispatches responses until every queue is drained.

const std = @import("std");
const raft = @import("raft_zig");

const allocator = std.testing.allocator;

const Raft = raft.Raft;
const MemoryStorage = raft.MemoryStorage;
const Message = raft.Message;
const MessageType = raft.MessageType;

pub const Peer = struct {
    raft: Raft,
    storage: MemoryStorage,

    pub fn deinit(self: *Peer) void {
        self.raft.deinit();
        self.storage.deinit(allocator);
    }
};

pub const Network = struct {
    peers: std.AutoHashMap(u64, *Peer),
    /// MessageTypes in this set are dropped by `filter`. Tests use it to
    /// simulate partitions or message loss.
    ignored: std.AutoHashMap(MessageType, void),

    pub fn init() Network {
        return .{
            .peers = std.AutoHashMap(u64, *Peer).init(allocator),
            .ignored = std.AutoHashMap(MessageType, void).init(allocator),
        };
    }

    pub fn deinit(self: *Network) void {
        var it = self.peers.valueIterator();
        while (it.next()) |p| {
            p.*.deinit();
            allocator.destroy(p.*);
        }
        self.peers.deinit();
        self.ignored.deinit();
        self.* = undefined;
    }

    pub fn ignoreMessageType(self: *Network, t: MessageType) !void {
        try self.ignored.put(t, {});
    }

    pub fn getPeer(self: *Network, id: u64) ?*Peer {
        return self.peers.get(id);
    }

    /// Dispatch a batch of messages. The network does NOT take ownership of
    /// the input slice — caller-owned messages stay valid after this returns.
    /// Outbound messages generated by peers during dispatch are owned by the
    /// network and freed before return.
    pub fn send(self: *Network, messages: []const Message) !void {
        var inbox: std.ArrayList(Message) = .empty;
        defer {
            for (inbox.items) |*m| m.deinit(allocator);
            inbox.deinit(allocator);
        }
        for (messages) |m| try inbox.append(allocator, try cloneMessage(allocator, m));

        while (inbox.items.len > 0) {
            // Take the message out of the inbox so subsequent appends don't
            // invalidate our pointer. The message's owned fields are freed at
            // the end of this iteration.
            var msg = inbox.swapRemove(inbox.items.len - 1);
            defer msg.deinit(allocator);

            if (!self.filter(&msg)) continue;

            // Local messages (hup, beat, check_quorum) have `to == 0` and are
            // routed back to the sender. Everything else routes by `to`.
            const target = if (msg.to == 0) msg.from else msg.to;
            const peer = self.peers.get(target) orelse continue;
            try peer.raft.step(&msg);
            try persistPeer(peer);
            try self.drainInto(peer, &inbox);
        }
    }

    /// Read all outbound messages from `peer`, removing them from the peer's
    /// outbox, and append deep-cloned copies to `inbox`. The peer's outbox
    /// is then cleared (the originals are gone, the inbox owns its copies).
    fn drainInto(self: *Network, peer: *Peer, inbox: *std.ArrayList(Message)) !void {
        _ = self;
        for (peer.raft.messages.items) |m| {
            try inbox.append(allocator, try cloneMessage(allocator, m));
        }
        // The peer still owns the original messages; clear its outbox without
        // freeing the individual entries because we transferred ownership to
        // the inbox via clone. To keep ownership semantics simple, we deinit
        // each peer's outbound message here and let the inbox clones stand.
        for (peer.raft.messages.items) |*m| m.deinit(allocator);
        peer.raft.messages.clearRetainingCapacity();
    }

    /// Returns true if the message should be delivered. Drops ignored types
    /// by returning false. Mutates nothing.
    fn filter(self: *Network, m: *Message) bool {
        if (self.ignored.contains(m.msg_type)) return false;
        return true;
    }
};

/// Deep-clone a Message: duplicates entries, snapshot, and context so the
/// returned value is fully owned and independently freeable.
fn cloneMessage(alloc: std.mem.Allocator, src: Message) !Message {
    var entries: []raft.Entry = &.{};
    if (src.entries.len > 0) {
        entries = try alloc.alloc(raft.Entry, src.entries.len);
        for (src.entries, 0..) |e, i| {
            entries[i] = .{
                .entry_type = e.entry_type,
                .term = e.term,
                .index = e.index,
                .data = if (e.data.len > 0) try alloc.dupe(u8, e.data) else &.{},
                .context = if (e.context.len > 0) try alloc.dupe(u8, e.context) else &.{},
                .checksum = e.checksum,
            };
        }
    }
    errdefer {
        for (entries) |*e| e.deinit(alloc);
        alloc.free(entries);
    }

    var snapshot: ?raft.Snapshot = null;
    if (src.snapshot) |s| {
        snapshot = .{
            .data = if (s.data.len > 0) try alloc.dupe(u8, s.data) else &.{},
            .metadata = .{
                .index = s.metadata.index,
                .term = s.metadata.term,
                .conf_state = .{
                    .voters = if (s.metadata.conf_state.voters.len > 0) try alloc.dupe(u64, s.metadata.conf_state.voters) else &.{},
                    .learners = if (s.metadata.conf_state.learners.len > 0) try alloc.dupe(u64, s.metadata.conf_state.learners) else &.{},
                    .voters_outgoing = if (s.metadata.conf_state.voters_outgoing.len > 0) try alloc.dupe(u64, s.metadata.conf_state.voters_outgoing) else &.{},
                    .learners_next = if (s.metadata.conf_state.learners_next.len > 0) try alloc.dupe(u64, s.metadata.conf_state.learners_next) else &.{},
                    .auto_leave = s.metadata.conf_state.auto_leave,
                },
            },
        };
    }
    errdefer if (snapshot) |*s| s.deinit(alloc);

    var context: []u8 = &.{};
    if (src.context.len > 0) context = try alloc.dupe(u8, src.context);
    errdefer if (context.len > 0) alloc.free(context);

    return .{
        .msg_type = src.msg_type,
        .to = src.to,
        .from = src.from,
        .term = src.term,
        .log_term = src.log_term,
        .index = src.index,
        .entries = entries,
        .commit = src.commit,
        .commit_term = src.commit_term,
        .snapshot = snapshot,
        .request_snapshot = src.request_snapshot,
        .reject = src.reject,
        .reject_hint = src.reject_hint,
        .context = context,
        .priority = src.priority,
    };
}

/// Move any unstable entries from the raft's log into storage, then notify
/// the raft so the leader can advance its commit index. Mirrors what the
/// production raftor loop does after each `Ready`.
fn persistPeer(peer: *Peer) !void {
    const r = &peer.raft;
    const unstable_ents = r.raft_log.unstable.entries.items;
    if (unstable_ents.len > 0) {
        try peer.storage.append(allocator, unstable_ents);
        const last = unstable_ents[unstable_ents.len - 1];
        // Order matters: stableEntries must move the unstable offset forward
        // before onPersistEntries checks maybePersist, otherwise the entry
        // still appears to be in the unstable range and maybePersist no-ops.
        r.raft_log.stableEntries(last.index, last.term);
        try r.onPersistEntries(last.index, last.term);
    }
}

/// Build a N-node network with the given voter set. Each peer gets a fresh
/// MemoryStorage seeded with the same ConfState and a deterministic PRNG seed.
pub fn newNetwork(peer_ids: []const u64) !Network {
    var net = Network.init();
    errdefer net.deinit();

    for (peer_ids) |id| {
        const peer = try allocator.create(Peer);
        errdefer allocator.destroy(peer);
        peer.* = .{
            .raft = undefined,
            .storage = MemoryStorage.init(),
        };

        const voters = try allocator.dupe(u64, peer_ids);
        var cs = raft.ConfState{ .voters = voters };
        try peer.storage.setRaftState(allocator, .{ .conf_state = cs });
        cs.deinit(allocator);

        var config = raft.defaultConfig();
        config.id = id;
        config.election_tick = 10;
        config.heartbeat_tick = 1;
        // Distinct seed per peer so election timeouts don't all fire together.
        config.election_timeout_seed = id * 0xDEAD;

        // Build Raft AFTER storage is at its final heap address; the Storage
        // vtable captures `&storage` and would dangle if we re-moved it.
        peer.raft = try Raft.init(allocator, config, peer.storage.asStorage());

        try net.peers.put(id, peer);
    }
    return net;
}
